'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Resources
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyCompany("Outercurve Foundation"),  _
 Assembly: AssemblyCopyright("Copyright © 2012 Outercurve Foundation."),  _
 Assembly: AssemblyVersion("1.2.2.1"),  _
 Assembly: AssemblyFileVersion("1.2.2.1"),  _
 Assembly: AssemblyInformationalVersion("1.2.2.1")> 

