// Copyright (c) 2015, Outercurve Foundation.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// - Redistributions of source code must  retain  the  above copyright notice, this
//   list of conditions and the following disclaimer.
//
// - Redistributions in binary form  must  reproduce the  above  copyright  notice,
//   this list of conditions  and  the  following  disclaimer in  the documentation
//   and/or other materials provided with the distribution.
//
// - Neither  the  name  of  the  Outercurve Foundation  nor   the   names  of  its
//   contributors may be used to endorse or  promote  products  derived  from  this
//   software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,  BUT  NOT  LIMITED TO, THE IMPLIED
// WARRANTIES  OF  MERCHANTABILITY   AND  FITNESS  FOR  A  PARTICULAR  PURPOSE  ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL,  SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO,  PROCUREMENT  OF  SUBSTITUTE  GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)  HOWEVER  CAUSED AND ON
// ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT  LIABILITY,  OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING  IN  ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal {
    
    public partial class SpaceEditDetails {
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.HtmlControls.HtmlTable tblEditPackage;
        protected System.Web.UI.WebControls.Label lblSpaceName;
        protected System.Web.UI.WebControls.TextBox txtName;
        protected System.Web.UI.WebControls.RequiredFieldValidator nameValidator;
        protected System.Web.UI.WebControls.Label lblComments;
        protected System.Web.UI.WebControls.TextBox txtComments;
        protected System.Web.UI.WebControls.Label lblCreationDate;
        protected WebsitePanel.Portal.CalendarControl PurchaseDate;
        protected System.Web.UI.WebControls.Label lblHostingPlan;
        protected System.Web.UI.WebControls.DropDownList ddlPlan;
        protected System.Web.UI.WebControls.RequiredFieldValidator planValidator;
        protected System.Web.UI.WebControls.Label lblTargetServer;
        protected WebsitePanel.Portal.ServerDetails serverDetails;
        protected WebsitePanel.Portal.CollapsiblePanel secAddons;
        protected System.Web.UI.WebControls.Panel AddonsPanel;
        protected System.Web.UI.WebControls.Button btnAddAddon;
        protected System.Web.UI.WebControls.GridView gvAddons;
        protected WebsitePanel.Portal.CollapsiblePanel secQuotas;
        protected System.Web.UI.WebControls.Panel QuotasPanel;
        protected System.Web.UI.HtmlControls.HtmlTable tblQuotas;
        protected System.Web.UI.HtmlControls.HtmlTable tblOverrideQuotas;
        protected System.Web.UI.WebControls.RadioButton rbPlanQuotas;
        protected System.Web.UI.WebControls.RadioButton rbPackageQuotas;
        protected WebsitePanel.Portal.SpaceQuotasControl packageQuotas;
        protected WebsitePanel.Portal.HostingPlansQuotas editPackageQuotas;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
